CCORE-671-ES-Refactor Builds
Unity-Technologies/createstudio_jenkins_lib pull request #37
Opened 2020-11-23 22:27 UTC by evensolberg-ffatg

### Purpose of this PR

Consolidate the build functionality into one function, which makes it easier to maintain and troubleshoot. A few of the "supporting" functions (most notably `UploadToAppCenter`) have been updated and made more robust as a consequence.

### PR Merge order

- This PR only

### Testing status

The Story and Showroom pipelines have been tested with this final version with the DEBUG flag on and off.

### Documentation status

In addition to an updated README, there is also a corresponding file to the `buildOnPlatform.groovy` file in the /docs/var/ folder that describes the new function.

### Technical risk

If the build function doesn't work, the pipeline doesn't build any Unity projects. Which is widely regarded as a Bad Thing (tm).

2020-11-23 22:59 UTC, bdebrincunity commented
This is great, I like the docs and debug info approach.

Only thing I wonder is if `vars/buildOnPlatform.groovy` is doing a little too much now? To me it might more sense if just did the build, and post build steps (like archiving or UploadToAppCenter) A) remained in the main unityBuildPipeline (for now) or B) went into a separate groovy script file.

2020-11-23 23:05 UTC, evensolberg-ffatg commented
> This is great, I like the docs and debug info approach.
> 
> Only thing I wonder is if `vars/buildOnPlatform.groovy` is doing a little too much now? To me it might more sense if just did the build, and post build steps (like archiving or UploadToAppCenter) A) remained in the main unityBuildPipeline (for now) or B) went into a separate groovy script file.

Yeah, we could potentially refactor the refactor. :)
At least for now it makes the pipeline very clean. But you have a point.

2020-11-23 23:06 UTC, jrowinski3d requested changes

2020-11-23 23:06 UTC, jrowinski3d commented on vars/buildOnPlatform.groovy
> +            if (isTargetBranch) {
I don't believe this is working as the current **isTargetBranch** is set to 
`Boolean isTargetBranch = "${BRANCH_NAME}".matches('main|staging|develop|release')`

yet you have build artifacts zipped up with no VERSION attached to it, instead you have a trailing **-** 
(builder-macos-.zip)
(builder-windows64-.zip

2020-11-23 23:06 UTC, jrowinski3d commented on vars/buildOnPlatform.groovy
> +            if (isTargetBranch) {
The way I got it to work in **develop** on DockerPush() is: 

`if ("${env.isTargetBranch}".toBoolean())`

2020-11-23 23:06 UTC, jrowinski3d commented on vars/buildOnPlatform.groovy
> +            if (isTargetBranch) {
In theory, you shouldn't have even been able to send builds to AppCenter yet they were in a PR. A bit strange though is that the AppCenter build versioning seems to be fine. Guessing due to line 14 in UploadToAppCenter

`String buildVer = System.getenv('VERSION') ?: '0.1.0'`

2020-11-23 23:06 UTC, evensolberg-ffatg commented on vars/UploadToAppCenter.groovy
> +            DEBUG: ''
Hmm. Maybe, yes.

2020-11-23 23:08 UTC, evensolberg-ffatg commented on vars/buildOnPlatform.groovy
> +            if (isTargetBranch) {
> I don't believe this is working as the current **isTargetBranch** is set to
> `Boolean isTargetBranch = "${BRANCH_NAME}".matches('main|staging|develop|release')`
> 
> yet you have build artifacts zipped up with no VERSION attached to it, instead you have a trailing **-**
> (builder-macos-.zip)
> (builder-windows64-.zip

Yeah, I agree. Will look into it.

2020-11-26 19:44 UTC, bdebrincunity approved these changes
Looks good! 👍

2020-11-26 19:56 UTC, merged