Upload macOS builds to AppCentre
Unity-Technologies/createstudio_jenkins_lib pull request #43
Opened 2020-12-02 01:19 UTC by bdebrincunity

### Purpose of this PR

Upload macOS builds after building them

**This is just a draft**

2020-12-10 16:24 UTC, bdebrincunity commented on vars/unityBuildPipeline.groovy
> +    Boolean isTargetBranch = "${BRANCH_NAME}".matches('main|staging|develop|release|PR-186|PR-48')
I'll remove this when the PR is approved

2020-12-10 16:34 UTC, evensolberg-ffatg commented on resources/com/createstudio/scripts/codesign_macos.sh
> +codesign --deep -f -v --timestamp -s "${developmentCertificate}" "${executable}"
Might want to add a newline at the end of the file.

2020-12-10 16:36 UTC, ryanbrookfield commented on vars/UploadToAppCenter.groovy
> +                releaseNotesWithoutDoubleQuotes = releaseNotesWithoutDoubleQuotes.replaceAll('"', '\'')
where is `releaseNotesWithoutDoubleQuotes` getting set initially?

2020-12-10 16:37 UTC, bdebrincunity commented on resources/com/createstudio/scripts/codesign_macos.sh
> +codesign --deep -f -v --timestamp -s "${developmentCertificate}" "${executable}"
done!

2020-12-10 16:38 UTC, bdebrincunity commented on vars/UploadToAppCenter.groovy
> +                releaseNotesWithoutDoubleQuotes = releaseNotesWithoutDoubleQuotes.replaceAll('"', '\'')
No where! I copied and pasted wrong 🤣

2020-12-10 16:38 UTC, evensolberg-ffatg submitted a review, later dismissed

2020-12-10 16:39 UTC, bdebrincunity commented on vars/UploadToAppCenter.groovy
> +                releaseNotesWithoutDoubleQuotes = releaseNotesWithoutDoubleQuotes.replaceAll('"', '\'')
Fixed, good catch

2020-12-10 17:28 UTC, jrowinski3d requested changes

2020-12-10 17:28 UTC, jrowinski3d commented on vars/runBokkenBuild.groovy
> +                        # Get SSH agent ready
Will the **iphone-vm** vm name/ bokken config ever change? Wonder if it might be a good idea to set it as a constant above all the shell steps to just override in the future.

I guess this is defined in the bokken yaml correct?

2020-12-10 17:28 UTC, jrowinski3d commented on vars/runBokkenBuild.groovy
> +                        # Get SSH agent ready
Possible to reduce the amount of duplicated code? Ie have a generic multiline shell that is used for both **mac** and **ios**.

And then an additional one for **mac**

ie.

```
bokken_steps = sh """
xyz
"""

bokken_mac_steps = sh """
additional steps
"""
if (target = mac) {
    $bokken_steps
    $additonal_steps
}
if (target = ios) {
    $bokken_steps
```

Just a thought, in case something has to be updated in the future will reduce the amount of places needs to be updated.

2020-12-10 17:28 UTC, jrowinski3d commented on vars/unityBuildPipeline.groovy
> +                                    def signedApp = runBokkenBuild(target: "${type}", projectPath: "${project}", bokkenConfig: 'com/createstudio/bokken/macos-xcode.yaml', serviceName: "${SERVICE_NAME
Can we change this to a generic **appPath** / **pathToApp** and do the same for iOS.

2020-12-10 17:28 UTC, jrowinski3d commented on vars/unityBuildPipeline.groovy
> +                                    def ipaPath = runBokkenBuild(target: "${type}", projectPath: "${project}", bokkenConfig: 'com/createstudio/bokken/macos-xcode.yaml', serviceName: "${SERVICE_NAME}"
See above comment in the **mac** stage

2020-12-10 21:18 UTC, bdebrincunity commented on vars/runBokkenBuild.groovy
> +                        # Get SSH agent ready
It shouldn't need to change, but it's not a very good name anyway.

So I changed it and made it a variable in the file.

2020-12-10 21:21 UTC, bdebrincunity commented on vars/runBokkenBuild.groovy
> +                        # Get SSH agent ready
I split it up in blocks: `shared` `macos` `ios`

2020-12-10 21:21 UTC, bdebrincunity commented on vars/unityBuildPipeline.groovy
> +                                    def signedApp = runBokkenBuild(target: "${type}", projectPath: "${project}", bokkenConfig: 'com/createstudio/bokken/macos-xcode.yaml', serviceName: "${SERVICE_NAME
Good call done

2020-12-10 21:26 UTC, evensolberg-ffatg approved these changes

2020-12-10 22:10 UTC, evensolberg-ffatg submitted a review, later dismissed

2020-12-10 22:17 UTC, jrowinski3d commented
@bdebrincunity One last thing if you dont mind please.

I see in the slack post that the name of the Download Link is just `Download-Ios: builds/Story.ipa` . I understand that the versioning doesn't play really well in Apple World. But you do have the archived artifacts as `story-ios-0.1.0-build.8.zip` in your builds. 

But can we have a link name to what's similar in the windows/macos outputs?

`Download-Windows: builder-windows64-0.1.0-build.7.zip`

2020-12-11 16:55 UTC, jrowinski3d submitted a review, later dismissed

2020-12-11 17:11 UTC, evensolberg-ffatg commented on vars/runBokkenBuild.groovy
> +                    def executable = "${SERVICE_NAME}".capitalize() + ".app"
This could be a `String`, presumably?

2020-12-11 17:12 UTC, jrowinski3d approved these changes

2020-12-11 17:14 UTC, bdebrincunity commented on vars/runBokkenBuild.groovy
> +                    def executable = "${SERVICE_NAME}".capitalize() + ".app"
sure done

2020-12-11 17:16 UTC, evensolberg-ffatg approved these changes

2020-12-11 17:19 UTC, jrowinski3d approved these changes

2020-12-11 17:21 UTC, merged