CCORE766 iOS / macOS build docs
Unity-Technologies/createstudio_jenkins_lib pull request #46
Opened 2020-12-07 22:36 UTC by bdebrincunity

### Purpose of this PR
Add docs for iOS and macOS builds

2020-12-07 22:38 UTC, evensolberg-ffatg commented on docs/ios_and_macos_builds.md
> +We use `bokken-cli` to interact with the service. Specifically we issue commands to create the job, poll it for rediness, copy files to the VM, run shell scripts, copy artifacts back from the VM and
"readiness"

2020-12-07 22:39 UTC, evensolberg-ffatg commented on docs/ios_and_macos_builds.md
> +```
```groovy

2020-12-07 22:41 UTC, evensolberg-ffatg requested changes
A couple of minor things, mainly cosmetic.

2020-12-07 22:41 UTC, bdebrincunity commented on docs/ios_and_macos_builds.md
> +We use `bokken-cli` to interact with the service. Specifically we issue commands to create the job, poll it for rediness, copy files to the VM, run shell scripts, copy artifacts back from the VM and
🔴 haha. Thanks!

2020-12-07 22:44 UTC, bdebrincunity commented on docs/ios_and_macos_builds.md
> +```
Do you think should include groovy as first line or remove from examples?

2020-12-07 23:06 UTC, evensolberg-ffatg commented on docs/ios_and_macos_builds.md
> +```
Include it - it enables syntax highlighting on some platforms.

2020-12-07 23:07 UTC, evensolberg-ffatg approved these changes

2020-12-07 23:09 UTC, bdebrincunity commented on docs/ios_and_macos_builds.md
> +```
Oo the colours! Thanks.

2020-12-08 04:31 UTC, jrowinski3d approved these changes

2020-12-08 04:32 UTC, merged