Ccore 673 unit tests
Unity-Technologies/createstudio_jenkins_lib pull request #52
Opened 2020-12-17 17:14 UTC by bdebrincunity

### Purpose of this PR

This PR runs unit tests (if supplied) against changed packages in `createstudio_core`. It does this by getting a list of changed packages in `createstudio_core/Packages` from `getChangedFileList`, resolving them to their respective Unity projects in `createstudio_core/Projects/Unity`, and then running it through `buildOnPlatform` with a new `test` target. The resulting XML is added to jobs test results via nunit. 

### Testing status

Currently only one package / project has unit tests: HttpProxy. This PR has been tested against it, and the results are as expected. It has also been tested against changes in packages that don't have unit tests (where it will try to run tests and realize there are none).

2020-12-17 18:25 UTC, jrowinski3d requested changes
Last comment would be to add more comments on steps to just understand what outputs/inputs are happening.

I guess an update to the `buildOnPlatform` doc would be handy in this case.

2020-12-17 18:25 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +                            String changedThings = getChangedFileList(params.DEBUG)
You shouldn't need to invoke this again, it was already done in the previous stage "Get Changed Files"
`String thingToBuild = getChangedFileList(params.DEBUG)`

2020-12-17 18:25 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +                                        packageName = sh(returnStdout: true, script: "echo ${folder} | cut -d'/' -f2 | rev | cut -d'.' -f 1 | rev").trim()
Could you add a comment here to show whats happening.

2020-12-17 18:25 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +                                                    testFilePath = sh(returnStdout: true, script: 'find . -name "*unit_tests.xml"').toString().minus('./').trim()
Use `findFiles` instead of `sh`. Save you running minus, trim etc etc

https://www.jenkins.io/doc/pipeline/steps/pipeline-utility-steps/#findfiles-find-files-in-the-workspace

2020-12-17 23:01 UTC, bdebrincunity commented on vars/buildOnPlatform.groovy
> +            echo "DEBUG: Docker image: gableroux/unity3d:2019.4.3f1-${platform}"
Cool idea. Replaced with a variable `UNITY_VERSION` that defaults `2019.4.3f1`, but can be overridden with env. 

`UNITY_VERSION = "${envVars.UNITY_VERSION ?: '2019.4.3f1'}"`

2020-12-17 23:02 UTC, bdebrincunity commented on vars/cloudBuildPipeline.groovy
> +                            String changedThings = getChangedFileList(params.DEBUG)
Fixed, and changed the variable name to make more sense globally.

2020-12-17 23:03 UTC, bdebrincunity commented on vars/cloudBuildPipeline.groovy
> +                                        packageName = sh(returnStdout: true, script: "echo ${folder} | cut -d'/' -f2 | rev | cut -d'.' -f 1 | rev").trim()
Does this make sense?
```
// Determine package name from its long identifier:
//      * Packages/com.unity.createstudio.clientrestapi > clientrestapi
// To do this we reverse the string, cut with '.' as the delimiter,
// take the first item, and the reverse the sting back. 
```

2020-12-17 23:19 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +                                        packageName = sh(returnStdout: true, script: "echo ${folder} | cut -d'/' -f2 | rev | cut -d'.' -f 1 | rev").trim()
yes thank you, the `revs` were turning me around and around

2020-12-18 00:30 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +                                        def packageUnityProject = sh(returnStdout: true, script: "find Projects/Unity -maxdepth 1 -type d -iname \"${packageName}*\"").trim()
This might be a easier way for you to resolve the name from the Package -> Package Project.

Each Unity Project has a `manifest.json` and `package.json` . Might be better off rendering those files.
```
[Localization]: (jenkins_testing) $ grep -R "com.unity.createstudio.localization" ./
./Packages/packages-lock.json:    "com.unity.createstudio.localization": {
./Packages/packages-lock.json:      "version": "file:../../../../Packages/com.unity.createstudio.localization",
./Packages/manifest.json:    "com.unity.createstudio.localization": "file:../../../../Packages/com.unity.createstudio.localization",
./Packages/manifest.json:      "com.unity.createstudio.localization"
[Localization]: (jenkins_testing) $ ls
Assets  Packages  ProjectSettings
[Localization]: (jenkins_testing) $ cat ./Packages/manifest.json
{
  "dependencies": {
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.createstudio.datamanager": "file:../../../../Packages/com.unity.createstudio.datamanager",
    "com.unity.createstudio.localization": "file:../../../../Packages/com.unity.createstudio.localization",
    "com.unity.ide.rider": "1.1.4",
    "com.unity.ide.vscode": "1.2.1",
    "com.unity.test-framework": "1.1.16",
    "com.unity.textmeshpro": "2.1.1",
    "com.unity.timeline": "1.2.15",
    "com.unity.ugui": "1.0.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  },
  "testables": [
      "com.unity.createstudio.localization"
  ]
}```

2020-12-18 17:26 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +                                        def packageUnityProject = sh(returnStdout: true, script: "find Projects/Unity -maxdepth 1 -type d -iname \"${packageName}*\"").trim()
Could use this to make it easier: https://www.jenkins.io/doc/pipeline/steps/pipeline-utility-steps/#readjson-read-json-from-files-in-the-workspace

2020-12-18 17:32 UTC, bdebrincunity commented on vars/cloudBuildPipeline.groovy
> +                                        def packageUnityProject = sh(returnStdout: true, script: "find Projects/Unity -maxdepth 1 -type d -iname \"${packageName}*\"").trim()
Haha already done, thanks for suggesting reading the file though! Go grep

2020-12-21 20:35 UTC, ryanbrookfield commented on vars/getChangedFileList.groovy
> +        String uniqueFiles = ''
this going to cause issues since its called before?

2020-12-21 20:42 UTC, ryanbrookfield commented on resources/com/createstudio/scripts/unity_build.sh
> +      exit 1
maybe not exit 1 if tests dont exist?? unless they are supposed to? Or have the message as 'error' vs 'warning'?

2020-12-21 20:44 UTC, bdebrincunity commented on vars/getChangedFileList.groovy
> +        String uniqueFiles = ''
You are right! I made this change before Jas fixed it in develop.

Using the version from develop now.

2020-12-21 20:44 UTC, evensolberg-ffatg approved these changes

2020-12-21 20:46 UTC, bdebrincunity commented on resources/com/createstudio/scripts/unity_build.sh
> +      exit 1
We want it to fail because a missing *tests.xml would mean that test failed in such a catastrophic way the file was not generated. I'll change it to error or error :)

2020-12-21 20:50 UTC, evensolberg-ffatg approved these changes

2020-12-21 20:51 UTC, ryanbrookfield approved these changes

2020-12-21 21:16 UTC, jrowinski3d approved these changes
Only thing I would suggest is to move this to its own function potentially. Doesn't have to happen now. Would be good to track it though in Jira and throw it in the backlog.

2020-12-21 21:20 UTC, merged

2020-12-21 21:25 UTC, bdebrincunity commented
Sounds good: new ticket https://jira.unity3d.com/browse/CCORE-907