CCORE-639: Create new AppCenter DLL client package for Showroom code assets
Unity-Technologies/createstudio_jenkins_lib pull request #59
Opened 2021-01-05 19:55 UTC by ryanbrookfield

…
### Purpose of this PR

[Desc of feature/change. Links to screenshots, design docs, user docs, etc. Remember reviewers may be outside your team, and not know your feature/area that should be explained more.]

### PR Merge order

- [ ] PR ###
- This PR

### Testing status

[Explanation of what’s tested, how tested and existing or new automation tests. Can include manual testing by self and/or QA. Specify test plans. Rarely acceptable to have no testing.]

- [ ] Added an automatic test
- [ ] Passed all automatic tests

### Documentation status

[Overview of how documentation is affected by this change. If there is no effect on documentation, explain why. Otherwise, state which sections are changed and why.]

- [ ] Updated [CHANGELOG](https://keepachangelog.com/en/1.0.0/)
- [ ] Updated README
- [ ] Commented all public classes, properties, and methods

### Technical risk

[Overall product level assessment of risk of change. Need technical risk & halo effect.]

2021-01-06 17:07 UTC, bdebrincunity submitted a review, later dismissed

2021-01-06 17:12 UTC, jrowinski3d requested changes

2021-01-06 17:12 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +                                def ShowroomAppCenterURL = UploadToAppCenter(version: 'showroom-0.1.0', projectType: "${PROJECT_TYPE}", projectPath: "${project}.zip", distGroups: 'ShowroomDevelopers'
whats the version here for and any reason its hard coded?

2021-01-06 17:18 UTC, ryanbrookfield commented on vars/cloudBuildPipeline.groovy
> +                                def ShowroomAppCenterURL = UploadToAppCenter(version: 'showroom-0.1.0', projectType: "${PROJECT_TYPE}", projectPath: "${project}.zip", distGroups: 'ShowroomDevelopers'
ahhhh, I see. Need to change that to something like `showroom-${envVars.VERSION}`

2021-01-06 17:26 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +                                def ShowroomAppCenterURL = UploadToAppCenter(version: 'showroom-0.1.0', projectType: "${PROJECT_TYPE}", projectPath: "${project}.zip", distGroups: 'ShowroomDevelopers'
Is this what will be reflected in the `release` name?

2021-01-06 17:47 UTC, ryanbrookfield commented on vars/cloudBuildPipeline.groovy
> +                                def ShowroomAppCenterURL = UploadToAppCenter(version: 'showroom-0.1.0', projectType: "${PROJECT_TYPE}", projectPath: "${project}.zip", distGroups: 'ShowroomDevelopers'
yes, so the appcenter package will look like the below based on UploadToAppCenter coding.

[String fullBuildVersion = "${BRANCH_NAME}-${buildVer}"](https://github.com/Unity-Technologies/createstudio_jenkins_lib/blob/develop/vars/UploadToAppCenter.groovy#L44)

where buildVer = version

2021-01-06 17:58 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +                                def ShowroomAppCenterURL = UploadToAppCenter(version: 'showroom-0.1.0', projectType: "${PROJECT_TYPE}", projectPath: "${project}.zip", distGroups: 'ShowroomDevelopers'
perfect, let me know how it goes!

2021-01-06 18:45 UTC, AnthonyV44 commented on vars/cloudBuildPipeline.groovy
> +                                def ShowroomAppCenterURL = UploadToAppCenter(version: 'showroom-0.1.0', projectType: "${PROJECT_TYPE}", projectPath: "${project}.zip", distGroups: 'ShowroomDevelopers'
@lairdm do you have a preference on the names of these AppCenter packages?

2021-01-06 22:05 UTC, ryanbrookfield commented on vars/cloudBuildPipeline.groovy
> +                                def ShowroomAppCenterURL = UploadToAppCenter(version: 'showroom-0.1.0', projectType: "${PROJECT_TYPE}", projectPath: "${project}.zip", distGroups: 'ShowroomDevelopers'
chatted around and looks like we are going to go with `${BRANCH_NAME}-showroom-${VERSION}`. Ill make the change and test. Packages should be visible tomorrow

2021-01-07 15:45 UTC, ryanbrookfield commented on vars/UploadToAppCenter.groovy
> +    String fullBuildVersion = ["${BRANCH_NAME}","${mergedArgs.projectName}","${buildVer}"].findAll({it != ''}).join('-')
Changed the logic here for the version string to be a bit more dynamic if you want to add in the Project name.

AppCenter will look like this:

![Screen Shot 2021-01-07 at 10 29 56 AM](https://user-images.githubusercontent.com/75379588/103912402-3f964180-50d5-11eb-9e67-2d50539d436e.png)

2021-01-07 17:15 UTC, jrowinski3d approved these changes

2021-01-07 17:21 UTC, bdebrincunity approved these changes

2021-01-07 17:28 UTC, merged