Enable CDS deploys from Jenkins
Unity-Technologies/createstudio_jenkins_lib pull request #68
Opened 2021-01-14 00:02 UTC by bdebrincunity

### Purpose of this PR

This PR will enable deploys of CDS (`api` / `db-migrator`) from Jenkins. The user can select the image (tag) to deploy and the release / env which to work on. For more details on how process works see the doc included in the PR: https://github.com/Unity-Technologies/createstudio_jenkins_lib/blob/feature/JAR_CCORE-858/docs/deployCDS.md

It includes work to pull secrets (namely kubeconfig) from vault, and scanning for images and tags from GCR. 

### PR Merge order

- This PR

### Testing status

So far this PR has been used to successfully test deploying to releases in the test environment. 

We are waiting for PRE to merge a credentail update to test deployment of staging releases. 

### Documentation status

Please see https://github.com/Unity-Technologies/createstudio_jenkins_lib/blob/feature/JAR_CCORE-858/docs/deployCDS.md

### Technical risk

Minimal-ish. Issues with this PR should only impact deployment, which is currently manual. Problems with the code could theoretically break existing releases which are used by the team for testing.

2021-01-14 17:58 UTC, evensolberg-ffatg commented on docs/deployCDS.md
> +The function operates mostly independtly at this time, and therefore doesn't have that many inputs.
Typo - independently

2021-01-14 18:03 UTC, evensolberg-ffatg approved these changes
Looks good. For a future version, you may want to add some more `if (DEBUG) {` statements throughout to output variables, in order to aid troubleshooting.

2021-01-14 18:03 UTC, bdebrincunity commented on docs/deployCDS.md
> +The function operates mostly independtly at this time, and therefore doesn't have that many inputs.
Thank you!

2021-01-14 18:04 UTC, bdebrincunity commented
> Looks good. For a future version, you may want to add some more `if (DEBUG) {` statements throughout to output variables, in order to aid troubleshooting.
Hmm that's actually a good call. I'll probably add some in today.

2021-01-14 18:25 UTC, jrowinski3d requested changes

2021-01-14 18:25 UTC, jrowinski3d commented on vars/cloudBuildPipeline.groovy
> +//                SendSlack(buildStatus: "${currentBuild.currentResult}", stageId: "${last_started}", projectMap: projectMap)
re-enable?

2021-01-14 18:25 UTC, jrowinski3d commented on vars/deployCDS.groovy
> +                      production:   [environment: 'prd']]
This is great. I'm wondering if there is a more dynamic way we can add to this?

Ie if we are going to have vault credentials and secrets pulled, do you think it would make sense to have this in vault?

Yesterday there was an ask from **showroom** team to create new environments. `showroom-dev1 / showroom-dev2 / showroom-dev3`

2021-01-14 18:25 UTC, jrowinski3d commented on vars/deployCDS.groovy
> +                            name: 'deploy_to_production')
Might be good to add a list of Submitters for `deploy_to_production` specificly?

Seems that there is a **submitter** option but it might be for the entire user input

```
submitter (optional)
User IDs and/or external group names of person or people permitted to respond to the input, separated by ','. Spaces will be trimmed. This means that "alice, bob, blah " is the same as "alice,bob,blah".
Note: Jenkins administrators are able to respond to the input regardless of the value of this parameter.
Type: String
```

2021-01-14 18:25 UTC, jrowinski3d commented on vars/deployCDS.groovy
> +        helmLimit = ''
add `helmLimit= -l tier=createdataservice-api -l tier=createdataservice-dbmigrator` just incase we add more to it?

Not sure if that is the correct syntax

2021-01-14 18:25 UTC, jrowinski3d commented on vars/deployCDS.groovy
> +    withCredentials([string(credentialsId: 'sa-develop', variable: "GC_KEY")]) {
Can we migrate this from Jenkins and into Vault? Once completed, there would be only 3. I can help with it if need be. Can add it to your existing PR

Will have to update `casc` and `vault`

2021-01-14 18:25 UTC, jrowinski3d commented on vars/deployCDS.groovy
> +                docker.image('quay.io/roboll/helmfile:helm3-v0.136.0').inside("-w /workspace -v \${PWD}:/workspace -it") {
can we switch this to v0.137.0 as it has the new flags for the wait for jobs? Ie we would be able to handle the dependency between migrations and the api

2021-01-14 18:25 UTC, jrowinski3d commented on vars/deployCDS.groovy
> +                docker.image('quay.io/roboll/helmfile:helm3-v0.136.0').inside("-w /workspace -v \${PWD}:/workspace -it") {
We might and probably will have to tweak our helmfile configs a bit.

2021-01-14 18:51 UTC, bdebrincunity commented on vars/cloudBuildPipeline.groovy
> +//                SendSlack(buildStatus: "${currentBuild.currentResult}", stageId: "${last_started}", projectMap: projectMap)
done!

2021-01-14 18:51 UTC, bdebrincunity commented on vars/deployCDS.groovy
> +                      production:   [environment: 'prd']]
Sureeee. How would you feel about a base64 encoded JSON string? Then we could read it in with readJSON.

2021-01-14 18:57 UTC, jrowinski3d commented on vars/deployCDS.groovy
> +                      production:   [environment: 'prd']]
yea would simplify it a bit for sure. I just dislike how many places we have to update right now to create a new environment.

we dont actually have to save it as base64 encoded. Vault has a `json` option

2021-01-14 18:57 UTC, bdebrincunity commented on vars/deployCDS.groovy
> +        helmLimit = ''
Hmm good call. 
```
   --selector value, -l value              Only run using the releases that match labels. Labels can take the form of foo=bar or foo!=bar.
                                           A release must match all labels in a group in order to be used. Multiple groups can be specified at once.
                                           --selector tier=frontend,tier!=proxy --selector tier=backend. Will match all frontend, non-proxy releases AND all backend releases.
                                           The name of a release can be used as a label. --selector name=myrelease
```
So I'll define selector like this: `helmLimit = '-l tier=createdataservice-dbmigrator -l tier=createdataservice-api'`

2021-01-14 18:58 UTC, bdebrincunity commented on vars/deployCDS.groovy
> +                      production:   [environment: 'prd']]
Oh sweet. I'll try that out.

2021-01-14 18:59 UTC, bdebrincunity commented on vars/deployCDS.groovy
> +    withCredentials([string(credentialsId: 'sa-develop', variable: "GC_KEY")]) {
Yeah if you don't mind that would be great! Agree we should add as much to vault as possible. Just wish PRE would review faster 🤣

2021-01-14 19:02 UTC, bdebrincunity commented on vars/deployCDS.groovy
> +                docker.image('quay.io/roboll/helmfile:helm3-v0.136.0').inside("-w /workspace -v \${PWD}:/workspace -it") {
Done!

2021-01-14 19:03 UTC, bdebrincunity commented on vars/deployCDS.groovy
> +                            name: 'deploy_to_production')
Ok cool. So ideally would you want the list of submitters hardcoded, defined in a repo (eg core, or here in libs?) or in a vault secret?

2021-01-14 19:18 UTC, jrowinski3d commented on vars/deployCDS.groovy
> +    withCredentials([string(credentialsId: 'sa-develop', variable: "GC_KEY")]) {
Ok, updated your PR in **casc** and updated with the new credentials in here:
https://vault.corp.unity3d.com/ui/vault/secrets/cloudbees/show/prd/masters/createstudio/gcp-cloudsql

2021-01-14 21:36 UTC, bdebrincunity commented on vars/deployCDS.groovy
> +    withCredentials([string(credentialsId: 'sa-develop', variable: "GC_KEY")]) {
Alright this is done anded tested. We're grabbing `SQL_PROXY_CREDENTIALS` from vault instead of the `GC_KEY` credential.

2021-01-18 23:46 UTC, bdebrincunity commented on vars/deployCDS.groovy
> +                      production:   [environment: 'prd']]
Done! https://github.com/Unity-Technologies/createstudio_orchestration/pull/38/files

2021-01-18 23:47 UTC, bdebrincunity commented on vars/deployCDS.groovy
> +                            name: 'deploy_to_production')
Implemented via the same orchestration/config approach: https://github.com/Unity-Technologies/createstudio_orchestration/pull/38/files

Deployers is checked twice. First when the deployCDS script starts, and again, at the input step.

2021-01-19 00:22 UTC, evensolberg-ffatg commented on docs/deployCDS.md
> +This function deploys CDS releases to our K8s environments via helmfile.
Create Data Service (CDS)

2021-01-19 00:24 UTC, evensolberg-ffatg approved these changes

2021-01-19 00:37 UTC, evensolberg-ffatg approved these changes

2021-01-19 04:45 UTC, jrowinski3d approved these changes

2021-01-19 17:16 UTC, bdebrincunity commented on vars/cloudBuildPipeline.groovy
> +                                DockerPush(dockerStrCredsID: 'sa-gcp-jenkins', images: [myAPIContainer.imageName(), myCLIContainer.imageName()])
Hey @jrowinski3d was doing one last check and noticed this has moved. It could have been me but I don't remember why? Do you know or should I put it back in the upload stage?

2021-01-19 17:38 UTC, bdebrincunity commented on vars/cloudBuildPipeline.groovy
> +                                DockerPush(dockerStrCredsID: 'sa-gcp-jenkins', images: [myAPIContainer.imageName(), myCLIContainer.imageName()])
It looks like it was moved before I got it so will assume is ok and fix later if needed 😁
https://github.com/Unity-Technologies/createstudio_jenkins_lib/blob/24082737f79a14c562e5927b7c581f3fa61d20cc/vars/cloudBuildPipeline.groovy

2021-01-19 17:39 UTC, merged